---
- hosts: all

  vars_files:
    - vars/main.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']
    - role: gantsign.oh-my-zsh
      when: configure_oh_my_zsh
      tags: ['oh_my_zsh']

  tasks:
    - ansible.builtin.import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - ansible.builtin.import_tasks: tasks/oh-my-zsh.yml
      when: configure_oh_my_zsh
      tags: ['oh_my_zsh']

    - ansible.builtin.import_tasks: tasks/pip-packages.yml
      tags: ['pip-packages']

    - block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']
