---
- name: Enable zsh-autosuggestions plugin
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    state: present

- name: Enable zsh-syntax-highlighting plugin
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
    state: present

- name: Enable pyenv shims, autocompletion and shell function
# https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: eval "$(pyenv init -)"
    state: present
